@metaURL=https://graph.facebook.com/v20.0/397080143485993/messages
@accessToken=EAAMJURCnZCdsBOZC7AqC5xDl82FOsEY3o1AFGioOBnsbACNOrdmhY50bD9ARYp1nWaIdqtdftUXaXerX9ZAnb5I5fINIr8UU1PCE3uZCxcDP7Kmd0PInTqFy80yaatG1nonJEeGlJ7fMKejBzjqoVNzUqLtFrmPfZC3cRqZAf1VQf8K6Uknm7w9PFJmABsu5y2vwZDZD

### DEFAULT TEMPLATE
POST {{metaURL}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{accessToken}}

{
	"messaging_product": "whatsapp",
	"to": "917809525145",
	"type": "template",
	"template": {
		"name": "hello_world",
		"language": {
			"code": "en_US"
		}
	}
}

### ASK BOT TEMPLATE
POST {{metaURL}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{accessToken}}

{
	"messaging_product": "whatsapp",
	"to": "917809525145",
	"type": "template",
	"template": {
		"name": "askbot",
		"language": {
			"code": "en"
		},
       "components": [
         {
           "type": "body",
           "parameters": [
               {
                   "type": "text",
                   "text": "Hello individual"
               }
           ]
         }
       ]
	}
}